--- 
title: "About Megan"
output: 
  html_document:
    css: ['CSSBackgrounds.css', 'CSSFonts.css', 'styles.css']
    includes:
      after_body: footer.html
---


I also have a longstanding love of natural history museums, which dates back to childhood visits to the Smithsonian and which was deepened by my REU experience working in the American Museum of Natural History. Here at Cornell, I'm fortunate to work with the Cornell University Insect Collection in a number of ways, ranging from specimen databasing to [exhibit curation](https://www.museumoftheearth.org/six-legged-science). I'm always interested in incorporating museum collections into my work. 

I would never have become a scientist without mentors who believed in me, and without exposure to a variety of evolutionary research. Now, mentorship and outreach are important components of my role as a graduate student. I have helped put together [museum exhibits](https://www.museumoftheearth.org/six-legged-science); write about [museums and biodiversity for general audiences](https://www.priweb.org/blog-post/insects-under-threat-the-role-of-natural-history-collections-in-biodiversity-conservation) and for [kids](https://kids.frontiersin.org/articles/10.3389/frym.2023.1048608); mentor undergraduate researchers; and share my research through [panels](https://youtu.be/HZ0WdZk84wM) and [talks](https://www.youtube.com/watch?v=S__qv9kKUlY). 